@user = barry
@password = S3nh@
@startAt = {{$datetime iso8601}}
@endAt = {{$datetime iso8601}}

# @name create-user
POST http://localhost:8080/users/
Content-Type: application/json

{
  "username": "{{user}}",
  "name": "Reinaldo Correia",
  "password": "{{password}}"
}

###

# @name create-task
POST http://localhost:8080/tasks/
Authorization: Basic {{user}}:{{password}}
Content-Type: application/json

{
  "description": "Tarefa para testar projeto",
  "title": "Teste",
  "priority": "ALTA",
  "startAt": "{{startAt}}",
  "endAt": "{{endAt}}"
}

###

# @name list-tasks
GET http://localhost:8080/tasks/
Authorization: Basic {{user}}:{{password}}

###

# @name update-tasks
PUT http://localhost:8080/tasks/6c0be67d-0efd-4cdf-8b27-580d75866ffb
Authorization: Basic {{user}}:{{password}}
Content-Type: application/json

{
  "description": "Mudando titulo da task"
}
